Parses self.env, and creates a new dict only with keys whose value is not None..
#discussion_952

Prior error
```
Traceback (most recent call last):
  File "/Users/ben.toms/Library/AutoPkg/RecipeRepos/com.github.autopkg.nstrauss-recipes/VirusTotalReporter/VirusTotalReporter.py", line 376, in <module>
    PROCESSOR.execute_shell()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 656, in execute_shell
    self.parse_arguments()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 607, in parse_arguments
    update_data(self.env, key, value)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 455, in update_data
    a_dict[key] = do_variable_substitution(value)
TypeError: 'NoneType' object does not support item assignment
```